version/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, SelectField, FloatField, IntegerField
from flask_wtf.file import FileField, FileAllowed
from wtforms.validators import DataRequired

class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    disaster_type = SelectField('Disaster Type', choices=[('flood','Flood'),('cyclone','Cyclone'),('earthquake','Earthquake')])
    picture = FileField('Picture', validators=[FileAllowed(['jpg', 'png'])])
    longitude = FloatField('Longitude', validators=[DataRequired()])
    latitude = FloatField('Latitude', validators=[DataRequired()])
    area = IntegerField('Area (in cm<sup>2</sup>)', validators=[DataRequired()])
    floor = IntegerField('Floor', validators=[DataRequired()])
    landscape = SelectField('Landscape', choices=[('plateu','Plateu'),('mountains','Mountains')])
    submit = SubmitField('Post')

version/main/routes.py
from flask import Blueprint, request, render_template

from version.models import Post

main = Blueprint('main', __name__)

@main.route("/")
@main.route("/home")
def home():
    page = request.args.get('page',1, type=int)
    posts= Post.query.filter_by(status='APPROVED').order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('home1.html', posts=posts,title='Home',cur_route='main.home')

@main.route("/about")
def about():
    return render_template('about.html', title='About')

@main.route('/donate')
def donate():
    return render_template('donate.html',title='Donate')

version/posts/routes.py
from flask import Blueprint, render_template, url_for, flash, abort, request, redirect
from flask_login import current_user, login_required
import numpy as np
from sklearn.linear_model import LinearRegression
import pickle

from version import db
from version.models import Post 
from version.posts.forms import PostForm
from version.posts.utils import save_dpicture

posts = Blueprint('posts', __name__)

@posts.route("/post/approved", methods=['GET','POST'])
def approved_post():
    page = request.args.get('page',1, type=int)
    posts= Post.query.filter_by(status='APPROVED').order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('posts.html', title='Approved Posts', posts=posts, cur_route='posts.approved_post')

@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    image_file = url_for('static', filename='post_image/' + post.image_file)
    return render_template('post.html', title=post.title, post=post, image_file=image_file)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user, disaster_type=form.disaster_type.data, longitude=form.longitude.data, latitude=form.latitude.data, area=form.area.data, floor=form.floor.data, landscape=form.landscape.data)
        print(form.picture.data)
        if form.picture.data:
            picture_file = save_dpicture(form.picture.data)
            post.image_file = picture_file
        filename = 'finalized_model.sav'
        loaded_model = pickle.load(open(filename, 'rb'))
        post.cost=loaded_model.predict(np.array([[post.area,post.floor]]))
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='New Post',
                           form=form, legend='New Post')

@posts.route('/post/awaited', methods=['GET','POST'])
@login_required
def awaited_post():
    if current_user.user_type != 'INTERMEDIATOR':
        abort(403)
    page = request.args.get('page',1, type=int)
    posts= Post.query.filter_by(status='AWAITED').order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('posts.html', title='Awaited posts', posts=posts, cur_route='posts.awaited_post')

@posts.route('/post/rejected', methods=['GET','POST'])
@login_required
def rejected_post():
    if current_user.user_type != 'INTERMEDIATOR':
        abort(403)
    page = request.args.get('page',1, type=int)
    posts= Post.query.filter_by(status='REJECTED').order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('posts.html', title='Rejected posts', posts=posts, cur_route='posts.rejected_post')

@posts.route('/post/all', methods=['GET','POST'])
@login_required
def all_post():
    if current_user.user_type != 'INTERMEDIATOR':
        abort(403)
    page = request.args.get('page',1, type=int)
    posts= Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('posts.html', title='All posts', posts=posts, cur_route='posts.all_post')

@posts.route('/post/reject/<int:post_id>', methods=['GET','POST'])
@login_required
def reject_post(post_id):
    if current_user.user_type != 'INTERMEDIATOR':
        abort(403)
    post = Post.query.get_or_404(post_id)
    post.status='REJECTED'
    db.session.commit()
    return redirect(url_for('posts.post', post_id=post.id))

@posts.route('/post/approve/<int:post_id>', methods=['GET','POST'])
@login_required
def approve_post(post_id):
    if current_user.user_type != 'INTERMEDIATOR':
        abort(403)
    post = Post.query.get_or_404(post_id)
    post.status='APPROVED'
    db.session.commit()
    return redirect(url_for('posts.post', post_id=post.id))

version/users/routes.py
from flask import render_template, redirect, url_for, flash, Blueprint, request
from flask_login import login_user, current_user, logout_user, login_required

from version import db, bcrypt
from version.models import User, Post
from version.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm)
from version.users.utils import save_picture, send_reset_email


users = Blueprint('users', __name__)

@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated and current_user.user_type!='AUTHORITY':
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        if current_user.is_authenticated and current_user.user_type == 'AUTHORITY':
            user.user_type=form.user_type.data
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    # current_user.user_type='AUTHORITY'
    # db.session.commit()
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)

@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)

@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account',
                           image_file=image_file, form=form)

@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

version/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <h1>About Page</h1>
{% endblock content %}

version/templates/donate.html
{% extends "layout.html" %}
{% block content %}
    <div class="bg-light rounded-lg p-4">
    <h1>Make Donation</h1>
    <a href="https://p-y.tm/F-4gM41" target="_blank" class="btn btn-outline-secondary">Donate here</a>
    </div>
{% endblock content %}

version/templates/home.html
{% extends "layout.html" %}
{% block content %}
    <h1>{{ title }}</h1>
    {% for post in posts.items %}
        <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
        <div class="media-body">
            <div class="article-metadata">
            <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
            <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            <span class="badge badge-secondary small">{{ post.status }}</span>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
        </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
        {% if posts.page == page_num %}
        <a class="btn btn-info mb-4" href="{{ url_for(cur_route, page=page_num) }}">{{ page_num }}</a>
        {% else %}
        <a class="btn btn-outline-info mb-4" href="{{ url_for(cur_route, page=page_num) }}">{{ page_num }}</a>
        {% endif %}
        {% else %}
        ...
        {% endif %}
    {% endfor %}
{% endblock content %}

version/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>DisasterAid</title>
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta content="" name="keywords">
  <meta content="" name="description">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='fonts/iconic/css/material-design-iconic-font.min.css') }}">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='vendor/animate/animate.css') }}">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='vendor/css-hamburgers/hamburgers.min.css') }}">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/util.css') }}">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main.css') }}">

  <!-- Favicons -->
  <link href="{{ url_for('static', filename='img/logo.jpg') }}" rel="icon">
  <link href="{{ url_for('static', filename='img/apple-touch-icon.png') }}" rel="apple-touch-icon">

  <!-- Bootstrap CSS File -->
  <link href="{{ url_for('static', filename='lib/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">

  <!-- Libraries CSS Files -->
  <link href="{{ url_for('static', filename='lib/font-awesome/css/font-awesome.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='lib/animate/animate.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='lib/ionicons/css/ionicons.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='lib/owlcarousel/assets/owl.carousel.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='lib/lightbox/css/lightbox.min.css') }}" rel="stylesheet">

  <!-- Main Stylesheet File -->
  <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">


  <!-- =======================================================
    Theme Name: DevFolio
    Theme URL: https://bootstrapmade.com/devfolio-bootstrap-portfolio-html-template/
    Author: BootstrapMade.com
    License: https://bootstrapmade.com/license/
  ======================================================= -->
</head>

<body id="page-top">
    <nav class="navbar navbar-expand-md bg-light navbar-light">
      <div class="container">  
      <!-- Brand -->
        <a class="navbar-brand" href="{{ url_for('main.home') }}">DisasterAid</a>
      
        <!-- Toggler/collapsibe Button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <!-- Navbar links -->
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
          <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('main.home') }}">Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('main.donate') }}">Donate</a>
                </li>
                {% if current_user.is_authenticated %}
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">Post</a>
                  <div class="dropdown-menu">
      
                    <a class="dropdown-item" style="background-opacity:0.8" href="{{ url_for('posts.new_post') }}">New Post</a>
                    <a class="dropdown-item" href="{{ url_for('users.user_posts',username=current_user.username) }}">My Posts</a>
                    {% if current_user.user_type=='INTERMEDIATOR' or current_user.user_type=='AUTHORITY' %}
                    <a class="dropdown-item" href="{{ url_for('posts.approved_post') }}">Approved Posts</a>
                    {% endif %}
                      {% if current_user.user_type=='INTERMEDIATOR' %}
                      
                    <a class="dropdown-item" href="{{ url_for('posts.all_post') }}">All Posts</a>
                    <a class="dropdown-item" href="{{ url_for('posts.awaited_post') }}">Awaited Posts</a>
                    <a class="dropdown-item" href="{{ url_for('posts.rejected_post') }}">Rejected Posts</a>
                    {% endif %}
                  </div>
                </li>
                {% if current_user.user_type=='AUTHORITY' %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('users.register') }}">Register</a>
                  </li>
                  {% endif %}
                  <li class="nav-item">
                      <a class="nav-link" href="{{ url_for('users.account') }}">Account</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                      </li>
      
              {% else %}
              <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('posts.approved_post') }}">Posts</a>
                </li>
              <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('users.login') }}">Login</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('users.register') }}">Register</a>
                </li>
              {% endif %} 
          </ul>
        </div>
      </div> 
      </nav>
  <!--/ Nav End /-->
  <main>
    <div class=" container pt-4">
      {% block content %}{% endblock %}
    </div>
  </main>
  

  <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>
  <div id="preloader"></div>

  <!-- JavaScript Libraries -->
  <script src="{{ url_for('static', filename='lib/jquery/jquery.min.js') }}"></script>
  <script src="{{ url_for('static', filename='lib/jquery/jquery-migrate.min.js') }}"></script>
  <script src="{{ url_for('static', filename='lib/popper/popper.min.js') }}"></script>
  <script src="{{ url_for('static', filename='lib/bootstrap/js/bootstrap.min.js') }}"></script>
  <script src="{{ url_for('static', filename='lib/easing/easing.min.js') }}"></script>
  <script src="{{ url_for('static', filename='lib/counterup/jquery.waypoints.min.js') }}"></script>
  <script src="{{ url_for('static', filename='lib/counterup/jquery.counterup.js') }}"></script>
  <script src="{{ url_for('static', filename='lib/owlcarousel/owl.carousel.min.js') }}"></script>
  <script src="{{ url_for('static', filename='lib/lightbox/js/lightbox.min.js') }}"></script>
  <script src="{{ url_for('static', filename='lib/typed/typed.min.js') }}"></script>

  <!-- Contact Form JavaScript File -->
  <script src="{{ url_for('static', filename='contactform/contactform.js') }}"></script>

  <!-- Template Main Javascript File -->
  <script src="{{ url_for('static', filename='js/main.js') }}"></script>


</body>
</html>
<style>
  .navbar-light .navbar-nav .nav-link {
    color: #0078ff;
    text-transform: uppercase;
    font-weight: 600;
    padding-right: .5rem;
    padding-left: .5rem;
    display: block;
    padding: .5rem 1rem;
}
.navbar-light .navbar-brand {
    color: #0078ff;
    font-size: 1.6rem;
    font-weight: 600;
}
body{
        background-image: url('{{ url_for('static',filename='img/bg-01.jpg') }}');
        background-size: cover;
    }
    .login100-form-btn{
        cursor: pointer;
    }
</style>

version/templates/login.html
{% extends "layout.html" %}
{% block content %}
<div>
		<div class="container-login100" style="background-image: url(''{{ url_for('static', filename='img/bg-01.jpg') }}');">
			<div class="wrap-login100 p-l-55 p-r-55 pt-5 pb-5">
				<form action="" method="post" class="login100-form validate-form" >
                        {{ form.hidden_tag() }}
					<span class="login100-form-title p-b-49">
						Login
					</span>

					<div class="wrap-input100 validate-input m-b-23" data-validate = "Username is required">
						<span class="label-input100">Username</span>
						{% if form.email.errors %}
                    {{ form.email(class="input100 is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="input100") }}
                {% endif %}
						<span class="focus-input100" data-symbol="&#xf206;"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Password is required">
						<span class="label-input100">Password</span>
						{% if form.password.errors %}
                    {{ form.password(class="input100 is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password(class="input100") }}
                {% endif %}
						<span class="focus-input100" data-symbol="&#xf190;"></span>
					</div>
					
					<div class="text-right p-t-8 p-b-31">
						<a href="{{ url_for('users.reset_request') }}">
							Forgot password?
						</a>
					</div>
					
					<div class="container-login100-form-btn">
						<div class="wrap-login100-form-btn">
							<div class="login100-form-bgbtn"></div>
                            {{ form.submit(class="login100-form-btn btn-primary") }}
						</div>
					</div>

					<div class="flex-col-c pt-5">
						<span class="txt1 pb-3">
							Need an account?
						</span>

						<a href="{{ url_for('users.register') }}" class="txt2">
							Sign Up
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>

{% endblock content %}

version/templates/post.html
{% extends "layout.html" %}
{% block content %}
<div class="bg-light rounded-lg p-4">
    <article class="media content-section">
        <img class="rounded-circle article-img mr-2" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
        <br>
        <div class="media-body">
            <a href="{{ url_for('users.user_posts', username=post.author.username) }}"><h2>By  {{ post.author.username }}</h2></a>
          <div class="article-metadata">
            {% if ((current_user.user_type == 'INTERMEDIATOR') and (post.status=='AWAITED')) %}
              <div>
                <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.approve_post', post_id=post.id) }}">Approve</a>
                <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#rejectModal">Reject</button>
              </div>
            {% else %}
              <div class="m-1">
                  <span class="btn btn-outline-primary">{{ post.status }}</span>
              </div>
            {% endif %}
          </div>
    
<div class="card w-100" style="width: 18rem;">
    <img class="card-img-top" src="{{ url_for('static', filename='post_image/' + post.image_file) }}" alt="Card image cap">
    <div class="card-body">
        <a href="{{ url_for('posts.post', post_id=post.id) }}"><h5 class="card-title">{{ post.title }}</h5></a>
        <h6 class="card-subtitle mb-2 text-muted">&#x20b9; {{ post.cost|round(2, 'floor') }}</h6>
        
        <p class="card-text">{{ post.content }}</p>
        <div id="map"></div>
      </div>
    <div class="card-footer">
            <small class="text-muted">Posted at: {{ post.date_posted.strftime('%Y-%m-%d') }}</small>
          </div>
</div>
</div>


        <style>
            /* Set the size of the div element that contains the map */
            #map {
              height: 400px;  /* The height is 400 pixels */
              width: 100%;  /* The width is the width of the web page */
             }
          </style>
    <script>
// Initialize and add the map
function initMap() {
  // The location of Uluru
  var uluru = {lat: {{ post.latitude }}, lng: {{ post.longitude }} };
  // The map, centered at Uluru
  var map = new google.maps.Map(
      document.getElementById('map'), {zoom: 10, center: uluru});
  // The marker, positioned at Uluru
  var marker = new google.maps.Marker({position: uluru, map: map});
}
    </script>
    <script async defer
    src="http://maps.googleapis.com/maps/api/js?key=AIzaSyAv8GHVQSr2TfpaQw42sj9iUXTg3uC68wU&callback=initMap">
    </script>





      <!-- <h2 class="article-title"> post.title </h2>
      <p class="article-content"> post.content </p> -->
    </div>
  </article>
  <!-- Modal -->
  <div class="modal fade" id="rejectModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Reject Post?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('posts.reject_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Reject">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

version/templates/posts.html
{% extends "layout.html" %}
{% block content %}
<div class="bg-light rounded-lg p-4">
    <h1>{{ title }}</h1>
    <div class="card-deck mb-3">
    {% for post in posts.items %}
    <div class="card" style="width: 18rem;">
        <img class="card-img-top" src="{{ url_for('static', filename='post_image/' + post.image_file) }}" alt="Card image cap">
        <div class="card-body">
            <a href="{{ url_for('posts.post', post_id=post.id) }}"><h5 class="card-title">{{ post.title }}</h5></a>
            <h6 class="card-subtitle mb-2 text-muted">&#x20b9; {{ post.cost|round(2, 'floor') }}</h6>
            <p class="card-text">{{ post.content }}</p>
            By <a href="{{ url_for('users.user_posts', username=post.author.username) }}" class="card-link">{{ post.author.username }}</a>
        </div>
        <div class="card-footer">
                <small class="text-muted">Posted at: {{ post.date_posted.strftime('%Y-%m-%d') }}</small>
              </div>
    </div>
    {% endfor %}
</div>

    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
        {% if posts.page == page_num %}
        <a class="btn btn-info mb-4" href="{{ url_for(cur_route, page=page_num) }}">{{ page_num }}</a>
        {% else %}
        <a class="btn btn-outline-info mb-4" href="{{ url_for(cur_route, page=page_num) }}">{{ page_num }}</a>
        {% endif %}
        {% else %}
        ...
        {% endif %}
    {% endfor %}
    </div>
{% endblock content %}

version/templates/user_posts.html
{% extends "layout.html" %}
{% block content %}
<div class="bg-light rounded-lg p-4">
    <h1 class="mb-3">Posts by {{ user.username }} ({{ posts.total }})</h1>
    <div class="card-deck mb-3">
        {% for post in posts.items %}
        <div class="card" style="width: 18rem;">
            <img class="card-img-top" src="{{ url_for('static', filename='post_image/' + post.image_file) }}" alt="Card image cap">
            <div class="card-body">
                <a href="{{ url_for('posts.post', post_id=post.id) }}"><h5 class="card-title">{{ post.title }}</h5></a>
                <h6 class="card-subtitle mb-2 text-muted">&#x20b9; {{ post.cost|round(2, 'floor') }}</h6>
                <p class="card-text">{{ post.content }}</p>
                By <a href="{{ url_for('users.user_posts', username=post.author.username) }}" class="card-link">{{ post.author.username }}</a>
            </div>
            <div class="card-footer">
                    <small class="text-muted">Posted at: {{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                  </div>
        </div>
        {% endfor %}
    </div>
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
    </div>
{% endblock content %}